site_name: minix analysis
site_author: Tarik Ronan Drevon

docs_dir: 'docs'
site_dir: 'site'

theme: readthedocs
markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code

nav:
- 'Index' : 'index.md'
- 'Building the image' : 'build.md'
- 'Run' : 
    - 'bootstrap' : 'bootstrap.md'
    - 'kernel init' : 'kernel_init.md'
    - 'init process' : 'init.md'
- 'Structure':
    - 'memory layout' : 'memory.md'
    - 'files' : 'files.md'